'use client';

import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'si';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.products': 'Products',
    'nav.about': 'About',
    'nav.gallery': 'Gallery',
    'nav.bbq_rentals': 'BBQ Rentals',
    'nav.contact': 'Contact',
    'nav.get_quote': 'Get Quote',
    
    // Home Page
    'home.hero.title': 'Premium Eco-Friendly Fuel',
    'home.hero.subtitle': 'High-quality firewood and coconut shell charcoal for sustainable energy. Perfect for homes, restaurants, and industrial use.',
    'home.hero.order_now': 'Order Now',
    'home.hero.view_products': 'View Products',
    'home.hero.view_gallery': 'View Gallery',
    'home.hero.bbq_rentals': 'BBQ Rentals',
    
    'home.why_choose.title': 'Why Choose EcoFuel Pro?',
    'home.why_choose.subtitle': 'We deliver premium quality, sustainable fuel solutions with unmatched customer service.',
    'home.why_choose.eco_friendly': '100% Eco-Friendly',
    'home.why_choose.eco_friendly_desc': 'Sustainably sourced materials that help reduce carbon footprint and protect our environment.',
    'home.why_choose.premium_quality': 'Premium Quality',
    'home.why_choose.premium_quality_desc': 'Carefully selected and processed materials ensuring consistent burn quality and maximum heat output.',
    'home.why_choose.fast_delivery': 'Fast Delivery',
    'home.why_choose.fast_delivery_desc': 'Reliable delivery service with flexible scheduling to meet your fuel needs when you need them.',
    'home.why_choose.trusted': 'Trusted by 1000+',
    'home.why_choose.trusted_desc': 'Serving homes, restaurants, and businesses with consistent quality and professional service.',
    
    'home.featured_products.title': 'Featured Products',
    'home.featured_products.subtitle': 'Discover our premium selection of eco-friendly fuel solutions for every need.',
    'home.featured_products.contact_to_order': 'Contact to Order',
    'home.featured_products.view_all': 'View All Products',
    
    'home.testimonials.title': 'What Our Customers Say',
    'home.testimonials.subtitle': 'Join thousands of satisfied customers who trust EcoFuel Pro for their fuel needs.',
    
    'home.contact_cta.title': 'Ready to Order Premium Fuel?',
    'home.contact_cta.subtitle': 'Get in touch with us today for competitive pricing and fast delivery. Our team is ready to help you find the perfect fuel solution.',
    'home.contact_cta.call_us': 'Call Us',
    'home.contact_cta.email_us': 'Email Us',
    'home.contact_cta.visit_us': 'Visit Us',
    'home.contact_cta.business_hours': 'Business Hours',
    'home.contact_cta.get_free_quote': 'Get Free Quote',
    'home.contact_cta.call_now': 'Call Now',
    
    // Products
    'products.title': 'Our Premium Products',
    'products.subtitle': 'Discover our complete range of eco-friendly firewood and coconut shell charcoal products, carefully selected and processed for maximum quality and performance.',
    'products.all': 'All',
    'products.firewood': 'Firewood',
    'products.charcoal': 'Charcoal',
    'products.bundles': 'Bundles',
    'products.rentals': 'Rentals',
    'products.custom_quote': 'Need a Custom Quote?',
    'products.custom_quote_desc': 'Contact us for bulk orders, custom specifications, or special pricing for commercial customers.',
    'products.get_custom_quote': 'Get Custom Quote',
    
    // Product Names
    'product.premium_oak_firewood': 'Premium Oak Firewood',
    'product.coconut_shell_charcoal': 'Coconut Shell Charcoal',
    'product.mixed_hardwood_bundle': 'Mixed Hardwood Bundle',
    'product.birch_firewood': 'Birch Firewood',
    'product.bbq_charcoal_premium': 'BBQ Charcoal Premium',
    'product.camping_fire_bundle': 'Camping Fire Bundle',
    'product.professional_bbq_grill': 'Professional BBQ Grill',
    'product.portable_bbq_station': 'Portable BBQ Station',
    'product.commercial_bbq_smoker': 'Commercial BBQ Smoker',
    
    // Common
    'common.per_cord': 'per cord',
    'common.per_bag': 'per 20kg bag',
    'common.per_bundle': 'per bundle',
    'common.per_day': 'per day',
    'common.view_details': 'View Details',
    'common.view_rentals': 'View Rentals',
    'common.contact_to_order': 'Contact to Order',
    'common.phone': '+1 (555) 123-4567',
    'common.email': 'info@ecofuelpro.com',
    'common.address': '123 Eco Street, Green City',
    
    // Footer
    'footer.quick_links': 'Quick Links',
    'footer.products_list': 'Products',
    'footer.contact_info': 'Contact Info',
    'footer.copyright': '© 2025 EcoFuel Pro. All rights reserved.',
    
    // About Page
    'about.title': 'About EcoFuel Pro',
    'about.subtitle': 'Leading the way in sustainable energy solutions with premium firewood and coconut shell charcoal for homes, restaurants, and businesses across the region.',
    'about.our_story': 'Our Story',
    'about.story_p1': 'Founded in 2018, EcoFuel Pro began with a simple yet powerful mission: to provide high-quality, sustainable fuel solutions that benefit both our customers and the environment. What started as a small family business has grown into a trusted regional supplier.',
    'about.story_p2': 'We recognized the growing demand for eco-friendly alternatives to traditional fuels and saw an opportunity to make a positive impact. By focusing on sustainably sourced firewood and innovative coconut shell charcoal, we\'ve been able to offer products that deliver exceptional performance while supporting environmental conservation.',
    'about.story_p3': 'Today, we proudly serve over 1,000 satisfied customers, from individual homeowners to large commercial establishments. Our commitment to quality, sustainability, and customer service remains as strong as ever.',
    'about.our_mission': 'Our Mission',
    'about.mission_text': 'To provide premium quality, sustainably sourced firewood and coconut shell charcoal that meets the energy needs of our customers while contributing to environmental conservation and supporting local communities.',
    'about.our_vision': 'Our Vision',
    'about.vision_text': 'To become the leading provider of eco-friendly fuel solutions, setting the standard for sustainability and quality in the industry while making clean energy accessible to everyone.',
    'about.core_values': 'Our Core Values',
    'about.sustainability_first': 'Sustainability First',
    'about.sustainability_desc': 'We\'re committed to protecting our environment through responsible sourcing and eco-friendly practices.',
    'about.premium_quality': 'Premium Quality',
    'about.premium_quality_desc': 'Every product is carefully selected and processed to meet the highest standards of quality and performance.',
    'about.customer_care': 'Customer Care',
    'about.customer_care_desc': 'Our customers are at the heart of everything we do. We build lasting relationships through exceptional service.',
    'about.our_journey': 'Our Journey',
    'about.journey_subtitle': 'Key milestones that have shaped our growth and commitment to excellence.',
    'about.company_founded': 'Company Founded',
    'about.company_founded_desc': 'Started with a vision to provide eco-friendly fuel solutions',
    'about.first_warehouse': '1st Warehouse',
    'about.first_warehouse_desc': 'Opened our first processing and storage facility',
    'about.customers_500': '500+ Customers',
    'about.customers_500_desc': 'Reached major milestone in customer satisfaction',
    'about.regional_expansion': 'Regional Expansion',
    'about.regional_expansion_desc': 'Expanded delivery network across three states',
    'about.happy_clients_1000': '1000+ Happy Clients',
    'about.happy_clients_1000_desc': 'Celebrating continued growth and customer loyalty',
    'about.by_numbers': 'EcoFuel Pro by the Numbers',
    'about.happy_customers': 'Happy Customers',
    'about.cords_delivered': 'Cords Delivered',
    'about.states_served': 'States Served',
    'about.customer_support': 'Customer Support',
    'about.ready_to_join': 'Ready to Join Our Family?',
    'about.join_subtitle': 'Experience the EcoFuel Pro difference with premium quality products and exceptional service. Contact us today to get started.',
    'about.get_started_today': 'Get Started Today',
    
    // Gallery Page
    'gallery.title': 'Our Gallery',
    'gallery.subtitle': 'Take a behind-the-scenes look at our operations, from production facilities to delivery services. See the quality and care that goes into every product.',
    'gallery.why_choose_rentals': 'Why Choose Our BBQ Rentals?',
    'gallery.all': 'All',
    'gallery.factory': 'Factory',
    'gallery.stores': 'Stores',
    'gallery.work_environment': 'Work Environment',
    'gallery.delivery': 'Delivery',
    'gallery.main_production_facility': 'Main Production Facility',
    'gallery.main_production_desc': 'Our state-of-the-art processing facility where we prepare premium firewood',
    'gallery.coconut_processing': 'Coconut Shell Processing',
    'gallery.coconut_processing_desc': 'Watch how we transform coconut shells into premium charcoal',
    'gallery.quality_control': 'Quality Control Station',
    'gallery.quality_control_desc': 'Every batch undergoes rigorous quality testing',
    'gallery.seasoning_area': 'Seasoning Area',
    'gallery.seasoning_desc': 'Firewood seasoning facility with controlled environment',
    'gallery.main_retail_store': 'Main Retail Store',
    'gallery.main_retail_desc': 'Our flagship store showcasing all product lines',
    'gallery.product_display': 'Product Display Area',
    'gallery.product_display_desc': 'Interactive displays help customers choose the right products',
    'gallery.customer_service': 'Customer Service Counter',
    'gallery.customer_service_desc': 'Friendly staff ready to help with your fuel needs',
    'gallery.team_meeting': 'Team Meeting',
    'gallery.team_meeting_desc': 'Our dedicated team planning daily operations',
    'gallery.safety_training': 'Safety Training Session',
    'gallery.safety_training_desc': 'Regular safety training ensures a secure work environment',
    'gallery.production_team': 'Production Team',
    'gallery.production_team_desc': 'Skilled workers ensuring quality at every step',
    'gallery.delivery_fleet': 'Delivery Fleet',
    'gallery.delivery_fleet_desc': 'Our modern trucks ensure safe and timely delivery',
    'gallery.loading_process': 'Loading Process',
    'gallery.loading_process_desc': 'Professional loading ensures products arrive in perfect condition',
    'gallery.customer_delivery': 'Customer Delivery',
    'gallery.customer_delivery_desc': 'Happy customers receiving their premium fuel products',
    'gallery.gps_tracking': 'GPS Tracking System',
    'gallery.gps_tracking_desc': 'Real-time tracking for all deliveries',
    'gallery.operations_numbers': 'Our Operations in Numbers',
    'gallery.production_facilities': 'Production Facilities',
    'gallery.retail_locations': 'Retail Locations',
    'gallery.team_members': 'Team Members',
    'gallery.delivery_vehicles': 'Delivery Vehicles',
    'gallery.want_to_visit': 'Want to Visit Our Facilities?',
    'gallery.visit_subtitle': 'Schedule a tour of our production facilities and see firsthand how we create premium quality firewood and coconut shell charcoal.',
    'gallery.schedule_tour': 'Schedule a Tour',
    
    // BBQ Rentals Page
    'bbq.title': 'BBQ Machine Rentals',
    'bbq.subtitle': 'Professional BBQ equipment rentals for events, parties, and catering. From intimate gatherings to large commercial events, we have the perfect BBQ solution.',
    'bbq.why_choose': 'Why Choose Our BBQ Rentals?',
    'bbq.professional_grade': 'Professional Grade',
    'bbq.professional_grade_desc': 'Commercial-quality equipment for perfect results',
    'bbq.delivery_setup': 'Delivery & Setup',
    'bbq.delivery_setup_desc': 'Full delivery, setup, and pickup service available',
    'bbq.fully_insured': 'Fully Insured',
    'bbq.fully_insured_desc': 'All equipment is fully insured and maintained',
    'bbq.support_24_7': '24/7 Support',
    'bbq.support_24_7_desc': 'Round-the-clock support during your rental period',
    'bbq.rental_packages': 'Rental Packages',
    'bbq.packages_subtitle': 'Choose the perfect BBQ package for your event size and requirements.',
    'bbq.basic_package': 'Basic BBQ Package',
    'bbq.premium_package': 'Premium BBQ Package',
    'bbq.commercial_package': 'Commercial BBQ Package',
    'bbq.per_day': 'per day',
    'bbq.people_15_25': '15-25 people',
    'bbq.people_25_50': '25-50 people',
    'bbq.people_50_plus': '50+ people',
    'bbq.basic_ideal': 'Perfect for small family gatherings and backyard parties',
    'bbq.premium_ideal': 'Great for medium-sized events and corporate gatherings',
    'bbq.commercial_ideal': 'Perfect for large events, festivals, and catering operations',
    'bbq.package_includes': 'Package Includes:',
    'bbq.selected': 'Selected',
    'bbq.select_package': 'Select Package',
    'bbq.additional_services': 'Additional Services',
    'bbq.services_subtitle': 'Enhance your BBQ rental experience with our professional add-on services.',
    'bbq.setup_breakdown': 'Setup & Breakdown Service',
    'bbq.setup_breakdown_desc': 'Professional setup and cleanup service',
    'bbq.chef_service': 'Chef Service',
    'bbq.chef_service_desc': 'Professional chef to handle all the grilling',
    'bbq.premium_charcoal_package': 'Premium Charcoal Package',
    'bbq.premium_charcoal_desc': 'High-quality coconut shell charcoal for enhanced flavor',
    'bbq.extended_rental': 'Extended Rental (Weekend)',
    'bbq.extended_rental_desc': 'Friday to Sunday rental package',
    'bbq.easy_booking': 'Easy Booking Process',
    'bbq.choose_package': 'Choose Package',
    'bbq.choose_package_desc': 'Select the BBQ package that fits your event size',
    'bbq.contact_us': 'Contact Us',
    'bbq.contact_us_desc': 'Call or email us with your event details and date',
    'bbq.confirm_booking': 'Confirm Booking',
    'bbq.confirm_booking_desc': 'We\'ll confirm availability and finalize your rental',
    'bbq.enjoy_event': 'Enjoy Your Event',
    'bbq.enjoy_event_desc': 'We deliver, set up, and you enjoy perfect BBQ',
    'bbq.ready_to_book': 'Ready to Book Your BBQ Rental?',
    'bbq.book_subtitle': 'Contact us today to check availability and get a custom quote for your event.',
    'bbq.book_now': 'Book Now',
    'bbq.call_for_quote': 'Call for Quote',
    
    // Contact Page
    'contact.title': 'Contact EcoFuel Pro',
    'contact.subtitle': 'Get in touch with our team for quotes, orders, or any questions about our premium firewood and coconut shell charcoal products.',
    'contact.call_us': 'Call Us',
    'contact.email_us': 'Email Us',
    'contact.visit_us': 'Visit Us',
    'contact.business_hours': 'Business Hours',
    'contact.mon_fri': 'Mon-Fri 8AM-6PM',
    'contact.support_24_7': '24/7 Support',
    'contact.mon_fri_hours': 'Mon-Fri: 8AM-6PM',
    'contact.weekend_hours': 'Sat: 9AM-4PM, Sun: Closed',
    'contact.send_message': 'Send us a Message',
    'contact.form_subtitle': 'Fill out the form below and we\'ll get back to you as soon as possible with a quote or answers to your questions.',
    'contact.full_name': 'Full Name',
    'contact.email_address': 'Email Address',
    'contact.phone_number': 'Phone Number',
    'contact.subject': 'Subject',
    'contact.select_subject': 'Select a subject',
    'contact.request_quote': 'Request Quote',
    'contact.place_order': 'Place Order',
    'contact.delivery_inquiry': 'Delivery Inquiry',
    'contact.product_information': 'Product Information',
    'contact.other': 'Other',
    'contact.message': 'Message',
    'contact.message_placeholder': 'Tell us about your needs, quantity requirements, delivery location, or any questions you have...',
    'contact.send_message_btn': 'Send Message',
    'contact.message_sent': 'Message Sent!',
    'contact.message_sent_desc': 'Thank you for contacting us. We\'ll get back to you within 24 hours.',
    'contact.find_location': 'Find Our Location',
    'contact.quick_questions': 'Quick Questions',
    'contact.delivery_areas': 'Delivery Areas',
    'contact.delivery_areas_desc': 'We deliver within 50 miles of our location',
    'contact.minimum_order': 'Minimum Order',
    'contact.minimum_order_desc': 'Half cord minimum for firewood delivery',
    'contact.payment_methods': 'Payment Methods',
    'contact.payment_methods_desc': 'Cash, check, or major credit cards accepted',
    'contact.bulk_pricing': 'Bulk Pricing',
    'contact.bulk_pricing_desc': 'Special rates available for large orders',
    'contact.need_assistance': 'Need Immediate Assistance?',
    'contact.assistance_subtitle': 'For urgent orders or delivery questions, call us directly or send a WhatsApp message.',
    'contact.call_now': 'Call Now',
    'contact.whatsapp': 'WhatsApp',
  },
  si: {
    // Navigation
    'nav.home': 'මුල් පිටුව',
    'nav.products': 'නිෂ්පාදන',
    'nav.about': 'අප ගැන',
    'nav.gallery': 'ගැලරිය',
    'nav.bbq_rentals': 'BBQ කුලියට',
    'nav.contact': 'සම්බන්ධතා',
    'nav.get_quote': 'මිල ගණන් ලබාගන්න',
    
    // Home Page
    'home.hero.title': 'ප්‍රිමියම් පරිසර හිතකාමී ඉන්ධන',
    'home.hero.subtitle': 'තිරසාර බලශක්තිය සඳහා උසස් තත්ත්වයේ ගිනිකූරු සහ පොල් කටු අඟුරු. නිවාස, අවන්හල් සහ කාර්මික භාවිතය සඳහා පරිපූර්ණයි.',
    'home.hero.order_now': 'දැන් ඇණවුම් කරන්න',
    'home.hero.view_products': 'නිෂ්පාදන බලන්න',
    'home.hero.view_gallery': 'ගැලරිය බලන්න',
    'home.hero.bbq_rentals': 'BBQ කුලියට',
    
    'home.why_choose.title': 'ඇයි EcoFuel Pro තෝරාගන්නේ?',
    'home.why_choose.subtitle': 'අපි අසමසම පාරිභෝගික සේවාව සමඟ ප්‍රිමියම් තත්ත්වයේ, තිරසාර ඉන්ධන විසඳුම් ලබා දෙමු.',
    'home.why_choose.eco_friendly': '100% පරිසර හිතකාමී',
    'home.why_choose.eco_friendly_desc': 'කාබන් පියසටහන අඩු කිරීමට සහ අපගේ පරිසරය ආරක්ෂා කිරීමට උපකාර වන තිරසාර ලෙස ලබාගත් ද්‍රව්‍ය.',
    'home.why_choose.premium_quality': 'ප්‍රිමියම් තත්ත්වය',
    'home.why_choose.premium_quality_desc': 'ස්ථාවර දහන තත්ත්වය සහ උපරිම තාප නිෂ්පාදනය සහතික කරමින් ප්‍රවේශමෙන් තෝරාගත් සහ සැකසූ ද්‍රව්‍ය.',
    'home.why_choose.fast_delivery': 'වේගවත් බෙදාහැරීම',
    'home.why_choose.fast_delivery_desc': 'ඔබට අවශ්‍ය වන විට ඔබේ ඉන්ධන අවශ්‍යතා සපුරාලීම සඳහා නම්‍යශීලී කාලසටහන් සමඟ විශ්වසනීය බෙදාහැරීමේ සේවාව.',
    'home.why_choose.trusted': '1000+ විසින් විශ්වාස කරන ලද',
    'home.why_choose.trusted_desc': 'ස්ථාවර තත්ත්වය සහ වෘත්තීය සේවාව සමඟ නිවාස, අවන්හල් සහ ව්‍යාපාර සේවා කිරීම.',
    
    'home.featured_products.title': 'විශේෂාංගගත නිෂ්පාදන',
    'home.featured_products.subtitle': 'සෑම අවශ්‍යතාවයක් සඳහාම අපගේ පරිසර හිතකාමී ඉන්ධන විසඳුම්වල ප්‍රිමියම් තේරීම සොයාගන්න.',
    'home.featured_products.contact_to_order': 'ඇණවුම් කිරීමට සම්බන්ධ වන්න',
    'home.featured_products.view_all': 'සියලුම නිෂ්පාදන බලන්න',
    
    'home.testimonials.title': 'අපගේ ගනුදෙනුකරුවන් කියන දේ',
    'home.testimonials.subtitle': 'ඔවුන්ගේ ඉන්ධන අවශ්‍යතා සඳහා EcoFuel Pro විශ්වාස කරන සෑම තෘප්තිමත් ගනුදෙනුකරුවන් දහස් ගණනකට එක්වන්න.',
    
    'home.contact_cta.title': 'ප්‍රිමියම් ඉන්ධන ඇණවුම් කිරීමට සූදානම්ද?',
    'home.contact_cta.subtitle': 'තරඟකාරී මිලකරණය සහ වේගවත් බෙදාහැරීම සඳහා අද අප සමඟ සම්බන්ධ වන්න. පරිපූර්ණ ඉන්ධන විසඳුම සොයා ගැනීමට ඔබට උදව් කිරීමට අපගේ කණ්ඩායම සූදානම්.',
    'home.contact_cta.call_us': 'අපට කතා කරන්න',
    'home.contact_cta.email_us': 'අපට ඊමේල් කරන්න',
    'home.contact_cta.visit_us': 'අප වෙත පැමිණෙන්න',
    'home.contact_cta.business_hours': 'ව්‍යාපාරික වේලාවන්',
    'home.contact_cta.get_free_quote': 'නොමිලේ මිල ගණන් ලබාගන්න',
    'home.contact_cta.call_now': 'දැන් කතා කරන්න',
    
    // Products
    'products.title': 'අපගේ ප්‍රිමියම් නිෂ්පාදන',
    'products.subtitle': 'උපරිම තත්ත්වය සහ කාර්ය සාධනය සඳහා ප්‍රවේශමෙන් තෝරාගත් සහ සැකසූ අපගේ පරිසර හිතකාමී ගිනිකූරු සහ පොල් කටු අඟුරු නිෂ්පාදනවල සම්පූර්ණ පරාසය සොයාගන්න.',
    'products.all': 'සියල්ල',
    'products.firewood': 'ගිනිකූරු',
    'products.charcoal': 'අඟුරු',
    'products.bundles': 'මිටි',
    'products.rentals': 'කුලියට',
    'products.custom_quote': 'අභිරුචි මිල ගණනක් අවශ්‍යද?',
    'products.custom_quote_desc': 'තොග ඇණවුම්, අභිරුචි පිරිවිතර, හෝ වාණිජ ගනුදෙනුකරුවන් සඳහා විශේෂ මිලකරණය සඳහා අප සමඟ සම්බන්ධ වන්න.',
    'products.get_custom_quote': 'අභිරුචි මිල ගණන් ලබාගන්න',
    
    // Product Names
    'product.premium_oak_firewood': 'ප්‍රිමියම් ඕක් ගිනිකූරු',
    'product.coconut_shell_charcoal': 'පොල් කටු අඟුරු',
    'product.mixed_hardwood_bundle': 'මිශ්‍ර දෘඩ ලී මිටිය',
    'product.birch_firewood': 'බර්ච් ගිනිකූරු',
    'product.bbq_charcoal_premium': 'BBQ අඟුරු ප්‍රිමියම්',
    'product.camping_fire_bundle': 'කඳවුරු ගිනි මිටිය',
    'product.professional_bbq_grill': 'වෘත්තීය BBQ ග්‍රිල්',
    'product.portable_bbq_station': 'අතේ ගෙන යා හැකි BBQ ස්ථානය',
    'product.commercial_bbq_smoker': 'වාණිජ BBQ දුම්කරණය',
    
    // Common
    'common.per_cord': 'කෝඩ් එකකට',
    'common.per_bag': 'කිලෝ 20 බෑගයකට',
    'common.per_bundle': 'මිටියකට',
    'common.per_day': 'දිනකට',
    'common.view_details': 'විස්තර බලන්න',
    'common.view_rentals': 'කුලියට බලන්න',
    'common.contact_to_order': 'ඇණවුම් කිරීමට සම්බන්ධ වන්න',
    'common.phone': '+1 (555) 123-4567',
    'common.email': 'info@ecofuelpro.com',
    'common.address': '123 Eco Street, Green City',
    
    // Footer
    'footer.quick_links': 'ඉක්මන් සබැඳි',
    'footer.products_list': 'නිෂ්පාදන',
    'footer.contact_info': 'සම්බන්ධතා තොරතුරු',
    'footer.copyright': '© 2025 EcoFuel Pro. සියලුම හිමිකම් ඇවිරිණි.',
    
    // About Page
    'about.title': 'EcoFuel Pro ගැන',
    'about.subtitle': 'කලාපය පුරා නිවාස, අවන්හල් සහ ව්‍යාපාර සඳහා ප්‍රිමියම් ගිනිකූරු සහ පොල් කටු අඟුරු සමඟ තිරසාර බලශක්ති විසඳුම්වල ප්‍රමුඛතාවය ගනිමින්.',
    'about.our_story': 'අපගේ කතාව',
    'about.story_p1': '2018 දී ආරම්භ කරන ලද EcoFuel Pro සරල නමුත් බලවත් මෙහෙවරක් සමඟ ආරම්භ විය: අපගේ ගනුදෙනුකරුවන්ට සහ පරිසරයට ප්‍රයෝජනවත් වන උසස් තත්ත්වයේ, තිරසාර ඉන්ධන විසඳුම් සැපයීම. කුඩා පවුල් ව්‍යාපාරයක් ලෙස ආරම්භ වූ දේ විශ්වසනීය කලාපීය සැපයුම්කරුවෙකු දක්වා වර්ධනය වී ඇත.',
    'about.story_p2': 'අපි සාම්ප්‍රදායික ඉන්ධන සඳහා පරිසර හිතකාමී විකල්ප සඳහා වන වර්ධනය වන ඉල්ලුම හඳුනාගෙන ධනාත්මක බලපෑමක් ඇති කිරීමේ අවස්ථාවක් දුටුවෙමු. තිරසාර ලෙස ලබාගත් ගිනිකූරු සහ නව්‍ය පොල් කටු අඟුරු කෙරෙහි අවධානය යොමු කිරීමෙන්, පරිසර සංරක්ෂණයට සහාය වන අතරම විශිෂ්ට කාර්ය සාධනයක් ලබා දෙන නිෂ්පාදන ලබා දීමට අපට හැකි වී ඇත.',
    'about.story_p3': 'අද, අපි පුද්ගලික නිවාස හිමියන්ගේ සිට විශාල වාණිජ ආයතන දක්වා 1,000 කට වඩා තෘප්තිමත් ගනුදෙනුකරුවන්ට සේවා කිරීම ගැන ආඩම්බර වෙමු. තත්ත්වය, තිරසාරත්වය සහ පාරිභෝගික සේවාව සඳහා අපගේ කැපවීම වෙන කවරදාකටත් වඩා ශක්තිමත්ව පවතී.',
    'about.our_mission': 'අපගේ මෙහෙවර',
    'about.mission_text': 'පරිසර සංරක්ෂණයට දායක වන අතර ප්‍රාදේශීය ප්‍රජාවන්ට සහාය වන අතරම අපගේ ගනුදෙනුකරුවන්ගේ බලශක්ති අවශ්‍යතා සපුරාලන ප්‍රිමියම් තත්ත්වයේ, තිරසාර ලෙස ලබාගත් ගිනිකූරු සහ පොල් කටු අඟුරු සැපයීම.',
    'about.our_vision': 'අපගේ දැක්ම',
    'about.vision_text': 'පරිසර හිතකාමී ඉන්ධන විසඳුම්වල ප්‍රමුඛ සැපයුම්කරු බවට පත්වීම, කර්මාන්තයේ තිරසාරත්වය සහ තත්ත්වය සඳහා ප්‍රමිතිය සැකසීම සහ සියල්ලන්ට පිරිසිදු බලශක්තිය ප්‍රවේශ්‍ය කිරීම.',
    'about.core_values': 'අපගේ මූලික වටිනාකම්',
    'about.sustainability_first': 'තිරසාරත්වය ප්‍රථමයි',
    'about.sustainability_desc': 'වගකීම් සහගත ප්‍රභවයන් සහ පරිසර හිතකාමී පිළිවෙත් හරහා අපගේ පරිසරය ආරක්ෂා කිරීමට අපි කැපවී සිටිමු.',
    'about.premium_quality': 'ප්‍රිමියම් තත්ත්වය',
    'about.premium_quality_desc': 'සෑම නිෂ්පාදනයක්ම ප්‍රවේශමෙන් තෝරාගෙන උසස් තත්ත්වයේ සහ කාර්ය සාධනයේ ප්‍රමිතීන් සපුරාලීම සඳහා සකසනු ලැබේ.',
    'about.customer_care': 'පාරිභෝගික සත්කාර',
    'about.customer_care_desc': 'අපගේ ගනුදෙනුකරුවන් අප කරන සෑම දෙයකම හදවතේ සිටිති. අපි විශිෂ්ට සේවාව හරහා කල්පවත්නා සබඳතා ගොඩනගමු.',
    'about.our_journey': 'අපගේ ගමන',
    'about.journey_subtitle': 'අපගේ වර්ධනය සහ විශිෂ්ටත්වයට කැපවීම හැඩගස්වා ඇති ප්‍රධාන සන්ධිස්ථාන.',
    'about.company_founded': 'සමාගම ආරම්භ කිරීම',
    'about.company_founded_desc': 'පරිසර හිතකාමී ඉන්ධන විසඳුම් සැපයීමේ දැක්මක් සමඟ ආරම්භ කරන ලදී',
    'about.first_warehouse': 'පළමු ගබඩාව',
    'about.first_warehouse_desc': 'අපගේ පළමු සැකසුම් සහ ගබඩා කිරීමේ පහසුකම විවෘත කරන ලදී',
    'about.customers_500': 'ගනුදෙනුකරුවන් 500+',
    'about.customers_500_desc': 'පාරිභෝගික තෘප්තිමත් භාවයේ ප්‍රධාන සන්ධිස්ථානයට ළඟා විය',
    'about.regional_expansion': 'කලාපීය ව්‍යාප්තිය',
    'about.regional_expansion_desc': 'ප්‍රාන්ත තුනක් පුරා බෙදාහැරීමේ ජාලය ව්‍යාප්ත කරන ලදී',
    'about.happy_clients_1000': 'සතුටු සේවාදායකයන් 1000+',
    'about.happy_clients_1000_desc': 'අඛණ්ඩ වර්ධනය සහ පාරිභෝගික පක්ෂපාතිත්වය සැමරීම',
    'about.by_numbers': 'සංඛ්‍යා අනුව EcoFuel Pro',
    'about.happy_customers': 'සතුටු ගනුදෙනුකරුවන්',
    'about.cords_delivered': 'බෙදාහරින ලද කෝඩ්',
    'about.states_served': 'සේවා කරන ප්‍රාන්ත',
    'about.customer_support': 'පාරිභෝගික සහාය',
    'about.ready_to_join': 'අපගේ පවුලට එක්වීමට සූදානම්ද?',
    'about.join_subtitle': 'ප්‍රිමියම් තත්ත්වයේ නිෂ්පාදන සහ විශිෂ්ට සේවාව සමඟ EcoFuel Pro වෙනස අත්විඳින්න. ආරම්භ කිරීමට අද අප සමඟ සම්බන්ධ වන්න.',
    'about.get_started_today': 'අද ආරම්භ කරන්න',
    
    // Gallery Page
    'gallery.title': 'අපගේ ගැලරිය',
    'gallery.subtitle': 'නිෂ්පාදන පහසුකම්වල සිට බෙදාහැරීමේ සේවා දක්වා අපගේ මෙහෙයුම් පිළිබඳ තිරය පිටුපස බැල්මක් ගන්න. සෑම නිෂ්පාදනයකටම යන තත්ත්වය සහ සත්කාර බලන්න.',
    'gallery.why_choose_rentals': 'ඇයි අපගේ BBQ කුලියට තෝරාගන්නේ?',
    'gallery.all': 'සියල්ල',
    'gallery.factory': 'කර්මාන්තශාලාව',
    'gallery.stores': 'වෙළඳසැල්',
    'gallery.work_environment': 'වැඩ පරිසරය',
    'gallery.delivery': 'බෙදාහැරීම',
    'gallery.main_production_facility': 'ප්‍රධාන නිෂ්පාදන පහසුකම',
    'gallery.main_production_desc': 'අපි ප්‍රිමියම් ගිනිකූරු සකස් කරන අපගේ අති නවීන සැකසුම් පහසුකම',
    'gallery.coconut_processing': 'පොල් කටු සැකසීම',
    'gallery.coconut_processing_desc': 'පොල් කටු ප්‍රිමියම් අඟුරු බවට පරිවර්තනය කරන ආකාරය බලන්න',
    'gallery.quality_control': 'තත්ත්ව පාලන මධ්‍යස්ථානය',
    'gallery.quality_control_desc': 'සෑම කණ්ඩායමක්ම දැඩි තත්ත්ව පරීක්ෂණයකට ලක් කරනු ලැබේ',
    'gallery.seasoning_area': 'කුළුබඩු ප්‍රදේශය',
    'gallery.seasoning_desc': 'පාලිත පරිසරයක් සමඟ ගිනිකූරු කුළුබඩු පහසුකම',
    'gallery.main_retail_store': 'ප්‍රධාන සිල්ලර වෙළඳසැල',
    'gallery.main_retail_desc': 'සියලුම නිෂ්පාදන පෙළ ප්‍රදර්ශනය කරන අපගේ ප්‍රමුඛ වෙළඳසැල',
    'gallery.product_display': 'නිෂ්පාදන ප්‍රදර්ශන ප්‍රදේශය',
    'gallery.product_display_desc': 'අන්තර්ක්‍රියාකාරී ප්‍රදර්ශන ගනුදෙනුකරුවන්ට නිවැරදි නිෂ්පාදන තෝරාගැනීමට උදව් කරයි',
    'gallery.customer_service': 'පාරිභෝගික සේවා කවුන්ටරය',
    'gallery.customer_service_desc': 'ඔබේ ඉන්ධන අවශ්‍යතා සමඟ උදව් කිරීමට සූදානම් මිත්‍රශීලී කාර්ය මණ්ඩලය',
    'gallery.team_meeting': 'කණ්ඩායම් රැස්වීම',
    'gallery.team_meeting_desc': 'දෛනික මෙහෙයුම් සැලසුම් කරන අපගේ කැපවූ කණ්ඩායම',
    'gallery.safety_training': 'ආරක්ෂණ පුහුණු සැසිය',
    'gallery.safety_training_desc': 'නිතිපතා ආරක්ෂණ පුහුණුව ආරක්ෂිත වැඩ පරිසරයක් සහතික කරයි',
    'gallery.production_team': 'නිෂ්පාදන කණ්ඩායම',
    'gallery.production_team_desc': 'සෑම පියවරකදීම තත්ත්වය සහතික කරන දක්ෂ කම්කරුවන්',
    'gallery.delivery_fleet': 'බෙදාහැරීමේ ගුවන් යානා',
    'gallery.delivery_fleet_desc': 'අපගේ නවීන ට්‍රක් රථ ආරක්ෂිත සහ කාලානුකූල බෙදාහැරීම සහතික කරයි',
    'gallery.loading_process': 'පැටවීමේ ක්‍රියාවලිය',
    'gallery.loading_process_desc': 'වෘත්තීය පැටවීම නිෂ්පාදන පරිපූර්ණ තත්ත්වයේ පැමිණීම සහතික කරයි',
    'gallery.customer_delivery': 'පාරිභෝගික බෙදාහැරීම',
    'gallery.customer_delivery_desc': 'ඔවුන්ගේ ප්‍රිමියම් ඉන්ධන නිෂ්පාදන ලබාගන්නා සතුටු ගනුදෙනුකරුවන්',
    'gallery.gps_tracking': 'GPS ලුහුබැඳීමේ පද්ධතිය',
    'gallery.gps_tracking_desc': 'සියලුම බෙදාහැරීම් සඳහා තත්‍ය කාලීන ලුහුබැඳීම',
    'gallery.operations_numbers': 'සංඛ්‍යා අනුව අපගේ මෙහෙයුම්',
    'gallery.production_facilities': 'නිෂ්පාදන පහසුකම්',
    'gallery.retail_locations': 'සිල්ලර ස්ථාන',
    'gallery.team_members': 'කණ්ඩායම් සාමාජිකයන්',
    'gallery.delivery_vehicles': 'බෙදාහැරීමේ වාහන',
    'gallery.want_to_visit': 'අපගේ පහසුකම් වෙත පැමිණීමට අවශ්‍යද?',
    'gallery.visit_subtitle': 'අපගේ නිෂ්පාදන පහසුකම්වල සංචාරයක් සැලසුම් කරන්න සහ අපි ප්‍රිමියම් තත්ත්වයේ ගිනිකූරු සහ පොල් කටු අඟුරු නිර්මාණය කරන ආකාරය සෘජුවම බලන්න.',
    'gallery.schedule_tour': 'සංචාරයක් සැලසුම් කරන්න',
    
    // BBQ Rentals Page
    'bbq.title': 'BBQ යන්ත්‍ර කුලියට',
    'bbq.subtitle': 'සිදුවීම්, සාද සහ ආහාර සේවා සඳහා වෘත්තීය BBQ උපකරණ කුලියට. සමීප රැස්වීම්වල සිට විශාල වාණිජ සිදුවීම් දක්වා, අපට පරිපූර්ණ BBQ විසඳුම ඇත.',
    'bbq.why_choose': 'ඇයි අපගේ BBQ කුලියට තෝරාගන්නේ?',
    'bbq.professional_grade': 'වෘත්තීය ශ්‍රේණිය',
    'bbq.professional_grade_desc': 'පරිපූර්ණ ප්‍රතිඵල සඳහා වාණිජ-තත්ත්වයේ උපකරණ',
    'bbq.delivery_setup': 'බෙදාහැරීම සහ සැකසීම',
    'bbq.delivery_setup_desc': 'සම්පූර්ණ බෙදාහැරීම, සැකසීම සහ ගැනීමේ සේවාව ලබා ගත හැකිය',
    'bbq.fully_insured': 'සම්පූර්ණයෙන්ම රක්ෂණය කර ඇත',
    'bbq.fully_insured_desc': 'සියලුම උපකරණ සම්පූර්ණයෙන්ම රක්ෂණය කර නඩත්තු කර ඇත',
    'bbq.support_24_7': '24/7 සහාය',
    'bbq.support_24_7_desc': 'ඔබේ කුලියට කාලය තුළ පැය 24 පුරා සහාය',
    'bbq.rental_packages': 'කුලියට පැකේජ',
    'bbq.packages_subtitle': 'ඔබේ සිදුවීමේ ප්‍රමාණය සහ අවශ්‍යතා සඳහා පරිපූර්ණ BBQ පැකේජය තෝරන්න.',
    'bbq.basic_package': 'මූලික BBQ පැකේජය',
    'bbq.premium_package': 'ප්‍රිමියම් BBQ පැකේජය',
    'bbq.commercial_package': 'වාණිජ BBQ පැකේජය',
    'bbq.per_day': 'දිනකට',
    'bbq.people_15_25': 'පුද්ගලයන් 15-25',
    'bbq.people_25_50': 'පුද්ගලයන් 25-50',
    'bbq.people_50_plus': 'පුද්ගලයන් 50+',
    'bbq.basic_ideal': 'කුඩා පවුල් රැස්වීම් සහ පිටිපස්සේ සාද සඳහා පරිපූර්ණයි',
    'bbq.premium_ideal': 'මධ්‍යම ප්‍රමාණයේ සිදුවීම් සහ ආයතනික රැස්වීම් සඳහා විශිෂ්ටයි',
    'bbq.commercial_ideal': 'විශාල සිදුවීම්, උත්සව සහ ආහාර සේවා මෙහෙයුම් සඳහා පරිපූර්ණයි',
    'bbq.package_includes': 'පැකේජයට ඇතුළත්:',
    'bbq.selected': 'තෝරාගත්',
    'bbq.select_package': 'පැකේජය තෝරන්න',
    'bbq.additional_services': 'අමතර සේවා',
    'bbq.services_subtitle': 'අපගේ වෘත්තීය අමතර සේවා සමඟ ඔබේ BBQ කුලියට අත්දැකීම වැඩිදියුණු කරන්න.',
    'bbq.setup_breakdown': 'සැකසීම සහ කඩා බිඳ දැමීමේ සේවාව',
    'bbq.setup_breakdown_desc': 'වෘත්තීය සැකසීම සහ පිරිසිදු කිරීමේ සේවාව',
    'bbq.chef_service': 'සූපවේදී සේවාව',
    'bbq.chef_service_desc': 'සියලුම ග්‍රිල් කිරීම හැසිරවීමට වෘත්තීය සූපවේදියා',
    'bbq.premium_charcoal_package': 'ප්‍රිමියම් අඟුරු පැකේජය',
    'bbq.premium_charcoal_desc': 'වැඩිදියුණු කළ රසය සඳහා උසස් තත්ත්වයේ පොල් කටු අඟුරු',
    'bbq.extended_rental': 'දීර්ඝ කුලියට (සති අන්තය)',
    'bbq.extended_rental_desc': 'සිකුරාදා සිට ඉරිදා කුලියට පැකේජය',
    'bbq.easy_booking': 'පහසු වෙන්කරවා ගැනීමේ ක්‍රියාවලිය',
    'bbq.choose_package': 'පැකේජය තෝරන්න',
    'bbq.choose_package_desc': 'ඔබේ සිදුවීමේ ප්‍රමාණයට ගැලපෙන BBQ පැකේජය තෝරන්න',
    'bbq.contact_us': 'අප සමඟ සම්බන්ධ වන්න',
    'bbq.contact_us_desc': 'ඔබේ සිදුවීමේ විස්තර සහ දිනය සමඟ අපට කතා කරන්න හෝ ඊමේල් කරන්න',
    'bbq.confirm_booking': 'වෙන්කරවා ගැනීම තහවුරු කරන්න',
    'bbq.confirm_booking_desc': 'අපි ලබා ගත හැකි බව තහවුරු කර ඔබේ කුලියට අවසන් කරන්නෙමු',
    'bbq.enjoy_event': 'ඔබේ සිදුවීම භුක්ති විඳින්න',
    'bbq.enjoy_event_desc': 'අපි බෙදාහරිමු, සකසමු, ඔබ පරිපූර්ණ BBQ භුක්ති විඳින්න',
    'bbq.ready_to_book': 'ඔබේ BBQ කුලියට වෙන්කරවා ගැනීමට සූදානම්ද?',
    'bbq.book_subtitle': 'ලබා ගත හැකි බව පරීක්ෂා කිරීමට සහ ඔබේ සිදුවීම සඳහා අභිරුචි මිල ගණනක් ලබා ගැනීමට අද අප සමඟ සම්බන්ධ වන්න.',
    'bbq.book_now': 'දැන් වෙන්කරවා ගන්න',
    'bbq.call_for_quote': 'මිල ගණන් සඳහා කතා කරන්න',
    
    // Contact Page
    'contact.title': 'EcoFuel Pro සමඟ සම්බන්ධ වන්න',
    'contact.subtitle': 'අපගේ ප්‍රිමියම් ගිනිකූරු සහ පොල් කටු අඟුරු නිෂ්පාදන පිළිබඳ මිල ගණන්, ඇණවුම් හෝ ඕනෑම ප්‍රශ්නයක් සඳහා අපගේ කණ්ඩායම සමඟ සම්බන්ධ වන්න.',
    'contact.call_us': 'අපට කතා කරන්න',
    'contact.email_us': 'අපට ඊමේල් කරන්න',
    'contact.visit_us': 'අප වෙත පැමිණෙන්න',
    'contact.business_hours': 'ව්‍යාපාරික වේලාවන්',
    'contact.mon_fri': 'සඳුදා-සිකුරාදා 8AM-6PM',
    'contact.support_24_7': '24/7 සහාය',
    'contact.mon_fri_hours': 'සඳුදා-සිකුරාදා: 8AM-6PM',
    'contact.weekend_hours': 'සෙනසුරාදා: 9AM-4PM, ඉරිදා: වසා',
    'contact.send_message': 'අපට පණිවිඩයක් යවන්න',
    'contact.form_subtitle': 'පහත පෝරමය පුරවන්න, අපි මිල ගණනක් හෝ ඔබේ ප්‍රශ්නවලට පිළිතුරු සමඟ හැකි ඉක්මනින් ඔබ වෙත ආපසු එන්නෙමු.',
    'contact.full_name': 'සම්පූර්ණ නම',
    'contact.email_address': 'ඊමේල් ලිපිනය',
    'contact.phone_number': 'දුරකථන අංකය',
    'contact.subject': 'විෂයය',
    'contact.select_subject': 'විෂයයක් තෝරන්න',
    'contact.request_quote': 'මිල ගණන් ඉල්ලීම',
    'contact.place_order': 'ඇණවුම දෙන්න',
    'contact.delivery_inquiry': 'බෙදාහැරීමේ විමසීම',
    'contact.product_information': 'නිෂ්පාදන තොරතුරු',
    'contact.other': 'වෙනත්',
    'contact.message': 'පණිවිඩය',
    'contact.message_placeholder': 'ඔබේ අවශ්‍යතා, ප්‍රමාණ අවශ්‍යතා, බෙදාහැරීමේ ස්ථානය හෝ ඔබට ඇති ඕනෑම ප්‍රශ්නයක් ගැන අපට කියන්න...',
    'contact.send_message_btn': 'පණිවිඩය යවන්න',
    'contact.message_sent': 'පණිවිඩය යවන ලදී!',
    'contact.message_sent_desc': 'අප සමඟ සම්බන්ධ වීම ගැන ස්තූතියි. අපි පැය 24ක් ඇතුළත ඔබ වෙත ආපසු එන්නෙමු.',
    'contact.find_location': 'අපගේ ස්ථානය සොයන්න',
    'contact.quick_questions': 'ඉක්මන් ප්‍රශ්න',
    'contact.delivery_areas': 'බෙදාහැරීමේ ප්‍රදේශ',
    'contact.delivery_areas_desc': 'අපි අපගේ ස්ථානයේ සිට සැතපුම් 50ක් ඇතුළත බෙදාහරිමු',
    'contact.minimum_order': 'අවම ඇණවුම',
    'contact.minimum_order_desc': 'ගිනිකූරු බෙදාහැරීම සඳහා අර්ධ කෝඩ් අවමයි',
    'contact.payment_methods': 'ගෙවීමේ ක්‍රම',
    'contact.payment_methods_desc': 'මුදල්, චෙක්පත හෝ ප්‍රධාන ක්‍රෙඩිට් කාඩ්පත් පිළිගනු ලැබේ',
    'contact.bulk_pricing': 'තොග මිලකරණය',
    'contact.bulk_pricing_desc': 'විශාල ඇණවුම් සඳහා විශේෂ ගාස්තු ලබා ගත හැකිය',
    'contact.need_assistance': 'ක්ෂණික සහාය අවශ්‍යද?',
    'contact.assistance_subtitle': 'හදිසි ඇණවුම් හෝ බෙදාහැරීමේ ප්‍රශ්න සඳහා, අපට සෘජුවම කතා කරන්න හෝ WhatsApp පණිවිඩයක් යවන්න.',
    'contact.call_now': 'දැන් කතා කරන්න',
    'contact.whatsapp': 'WhatsApp',
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}